import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join, relative } from 'node:path';

const require = createRequire(import.meta.url);
const rootDir = join(import.meta.dir, '..');
const outputFile = join(rootDir, 'src/server/.generated/skills-bundle.ts');

const SKIP = new Set(['.DS_Store', 'README.md', 'ThirdPartyNoticeText.txt', 'CHANGELOG.md', 'LICENSE']);

async function collectFiles(dir: string, base: string): Promise<Record<string, string>> {
  const files: Record<string, string> = {};
  const entries = await readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    if (SKIP.has(entry.name)) continue;
    const fullPath = join(dir, entry.name);

    if (entry.isDirectory()) {
      Object.assign(files, await collectFiles(fullPath, base));
    } else if (entry.isFile()) {
      const rel = relative(base, fullPath);
      const buf = await readFile(fullPath);
      files[rel] = buf.toString('base64');
    }
  }

  return files;
}

async function main() {
  const skillsPkgDir = dirname(require.resolve('skills/package.json'));
  const skillsPkg = JSON.parse(await readFile(join(skillsPkgDir, 'package.json'), 'utf-8'));

  const yamlPkgDir = dirname(require.resolve('yaml/package.json'));
  const yamlPkg = JSON.parse(await readFile(join(yamlPkgDir, 'package.json'), 'utf-8'));

  console.log(`Embedding skills@${skillsPkg.version} + yaml@${yamlPkg.version}`);

  const manifest: Record<string, string> = {};

  const skillsFiles = await collectFiles(skillsPkgDir, skillsPkgDir);
  for (const [path, data] of Object.entries(skillsFiles)) {
    manifest[`node_modules/skills/${path}`] = data;
  }

  const yamlFiles = await collectFiles(yamlPkgDir, yamlPkgDir);
  for (const [path, data] of Object.entries(yamlFiles)) {
    manifest[`node_modules/yaml/${path}`] = data;
  }

  const json = JSON.stringify(manifest);
  const base64 = Buffer.from(json, 'utf-8').toString('base64');

  const output = [
    '// AUTO-GENERATED by scripts/embed-skills.ts — do not edit manually',
    `export const SKILLS_BUNDLE_VERSION = ${JSON.stringify(skillsPkg.version)};`,
    `export const SKILLS_BUNDLE_DATA = ${JSON.stringify(base64)};`,
    '',
  ].join('\n');

  await mkdir(dirname(outputFile), { recursive: true });
  await writeFile(outputFile, output, 'utf-8');

  const sizeKb = Math.round(base64.length / 1024);
  console.log(`Bundle written to src/server/.generated/skills-bundle.ts (${sizeKb} KB base64)`);
}

main().catch((error) => {
  console.error('Failed to embed skills:', error);
  process.exit(1);
});
