import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join, relative } from 'node:path';

const require = createRequire(import.meta.url);
const rootDir = join(import.meta.dir, '..');
const outputFile = join(rootDir, 'src/server/.generated/skills-bundle.ts');

const SKIP = new Set([
  '.DS_Store',
  'README.md',
  'ThirdPartyNoticeText.txt',
  'CHANGELOG.md',
  'LICENSE',
]);

async function collectFiles(dir: string, base: string): Promise<Record<string, string>> {
  const files: Record<string, string> = {};
  const entries = await readdir(dir, { withFileTypes: true });

  for (const entry of entries) {
    if (SKIP.has(entry.name)) continue;
    const fullPath = join(dir, entry.name);

    if (entry.isDirectory()) {
      Object.assign(files, await collectFiles(fullPath, base));
    } else if (entry.isFile()) {
      const rel = relative(base, fullPath);
      const buf = await readFile(fullPath);
      files[rel] = buf.toString('base64');
    }
  }

  return files;
}

interface PackageManifest {
  dependencies?: Record<string, string>;
  name: string;
  version: string;
}

async function collectPackageTree(
  packageDir: string,
  manifest: Record<string, string>,
  versions: Map<string, string>
): Promise<PackageManifest> {
  const packageManifest = JSON.parse(
    await readFile(join(packageDir, 'package.json'), 'utf-8')
  ) as PackageManifest;
  const existingVersion = versions.get(packageManifest.name);

  if (existingVersion) {
    if (existingVersion !== packageManifest.version) {
      throw new Error(
        `Cannot flatten ${packageManifest.name}@${packageManifest.version}; ` +
          `${existingVersion} is already bundled`
      );
    }
    return packageManifest;
  }

  versions.set(packageManifest.name, packageManifest.version);

  const packageFiles = await collectFiles(packageDir, packageDir);
  for (const [path, data] of Object.entries(packageFiles)) {
    manifest[`node_modules/${packageManifest.name}/${path}`] = data;
  }

  const packageRequire = createRequire(join(packageDir, 'package.json'));
  for (const dependency of Object.keys(packageManifest.dependencies ?? {})) {
    const dependencyDir = dirname(packageRequire.resolve(`${dependency}/package.json`));
    await collectPackageTree(dependencyDir, manifest, versions);
  }

  return packageManifest;
}

async function main() {
  const skillsPkgDir = dirname(require.resolve('skills/package.json'));
  const manifest: Record<string, string> = {};
  const versions = new Map<string, string>();
  const skillsPkg = await collectPackageTree(skillsPkgDir, manifest, versions);

  console.log(
    `Embedding skills@${skillsPkg.version} with ${versions.size - 1} runtime dependencies`
  );

  const json = JSON.stringify(manifest);
  const base64 = Buffer.from(json, 'utf-8').toString('base64');

  const output = [
    '// AUTO-GENERATED by scripts/embed-skills.ts — do not edit manually',
    `export const SKILLS_BUNDLE_VERSION = ${JSON.stringify(skillsPkg.version)};`,
    `export const SKILLS_BUNDLE_DATA = ${JSON.stringify(base64)};`,
    '',
  ].join('\n');

  await mkdir(dirname(outputFile), { recursive: true });
  await writeFile(outputFile, output, 'utf-8');

  const sizeKb = Math.round(base64.length / 1024);
  console.log(`Bundle written to src/server/.generated/skills-bundle.ts (${sizeKb} KB base64)`);
}

main().catch((error) => {
  console.error('Failed to embed skills:', error);
  process.exit(1);
});
